name: "Monitor spec updates"

on:
  schedule:
    - cron: "0 0 * * *" # Midnight-ly

jobs:
  check:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
      pull-requests: "write"

    steps:
      - uses: "actions/checkout@v3"

      - name: "Update spec case files"
        run: "bin/update_spec_case_files.sh"

      - uses: "peter-evans/create-pull-request@v5"
        with:
          title: "Spec case updates"
          assignees: "broothie"
