name: "Monitor spec updates"

on: workflow_dispatch
#on:
#  schedule:
#    - cron: "0 0 * * *" # Daily

jobs:
  check:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
      pull-requests: "write"

    steps:
      - uses: "actions/checkout@v3"

      - uses: "ruby/setup-ruby@v1.152.0"
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: "Update spec case files"
        run: "bin/rake update_spec_case_files"

      - name: "Check for diff"
        run: "git diff"

      - uses: "peter-evans/create-pull-request@v5"
        with:
          title: "Spec case updates"
          assignees: "broothie"
